apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lookup-service.fullname" . }}-secret
  labels:
    {{- include "lookup-service.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DSN: {{ required "Please set up .Values.lookup.postgresDsn!" .Values.lookup.postgresDsn | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lookup-service.fullname" . }}-db-secret
  labels:
    {{- include "lookup-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  POSTGRES_USERNAME: {{ required "Please set up .Values.postgres.username!" .Values.postgres.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "Please set up .Values.postgres.password!" .Values.postgres.password | b64enc | quote }}
  POSTGRES_DATABASE: {{ required "Please set up .Values.postgres.database!" .Values.postgres.database | b64enc | quote }}
