name: unit-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: env up
        run: docker-compose up -d
      - name: unit testing
        run: source .envrc && make test